//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksEnerjiYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaBilgileri
    {
        public int ID { get; set; }
        public Nullable<int> YIL { get; set; }
        public Nullable<int> AY { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<int> FaturaYeriID { get; set; }
    
        public virtual FaturaYeri FaturaYeri { get; set; }
    }
}
