//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksEnerjiYonetimSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POLY_ENERJI : DbContext
    {
        public POLY_ENERJI()
            : base("name=POLY_ENERJI")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolumler> Bolumler { get; set; }
        public virtual DbSet<FaturaBilgileri> FaturaBilgileri { get; set; }
        public virtual DbSet<FaturaYeri> FaturaYeri { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Hedefler> Hedefler { get; set; }
        public virtual DbSet<AylikUretimVerileri> AylikUretimVerileri { get; set; }
        public virtual DbSet<MakineCalismaSureleri> MakineCalismaSureleri { get; set; }
        public virtual DbSet<Makine> Makine { get; set; }
        public virtual DbSet<View_Bolum_Aylik_Calisma_Sureleris> View_Bolum_Aylik_Calisma_Sureleris { get; set; }
        public virtual DbSet<View_Bolum_Aylik_Calisma_Sureleri_Detay> View_Bolum_Aylik_Calisma_Sureleri_Detay { get; set; }
        public virtual DbSet<View_Bolum_Aylik_Calisma_Suresi_Basinc> View_Bolum_Aylik_Calisma_Suresi_Basinc { get; set; }
    }
}
