//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksEnerjiYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakineCalismaSureleri
    {
        public int ID { get; set; }
        public int MakineID { get; set; }
        public Nullable<int> Yil { get; set; }
        public Nullable<int> Ay { get; set; }
        public Nullable<int> CalismaSuresi { get; set; }
        public string KayitEden { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<decimal> ToplamTuketimKwh { get; set; }
        public Nullable<decimal> BasincKWh { get; set; }
        public Nullable<int> BolumID { get; set; }
        public Nullable<bool> KayitliMi { get; set; }
        public Nullable<int> M3 { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Makine Makine { get; set; }
    }
}
