//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksEnerjiYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makine()
        {
            this.MakineCalismaSureleri = new HashSet<MakineCalismaSureleri>();
        }
    
        public int ID { get; set; }
        public string MakineNo { get; set; }
        public string MakineAdi { get; set; }
        public Nullable<int> Bolum { get; set; }
        public Nullable<decimal> KWH { get; set; }
        public string YrdTesisMakTipi { get; set; }
        public string BasincDegeri { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MakineCalismaSureleri> MakineCalismaSureleri { get; set; }
    }
}
