//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksEnerjiYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Bolum_Aylik_Calisma_Suresi_Basinc
    {
        public int row_num { get; set; }
        public Nullable<int> Yil { get; set; }
        public Nullable<int> Ay { get; set; }
        public string Bolum { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<int> m3 { get; set; }
        public string YrdTesisMakTipi { get; set; }
        public string BasincDegeri { get; set; }
    }
}
